[package]
authors = ["David LeGare <excaliburhissheath@gmail.com>"]
name = "hangry-river-horse"
version = "0.2.0"

[dependencies]
rand = "0.3.15"
rocket = "0.2.8"
rocket_codegen = "0.2.8"
rocket_contrib = "0.2.8"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
ws = "0.7.3"
